services:
  db:
    image: postgres:15
    container_name: exlibrisdomus-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
