 ▗▄▖ ▗▖ ▗▖▗▄▄▄▖▗▖ ▗▖ ▗▄▖ ▗▄▄▖  ▗▄▄▖
▐▌ ▐▌▐▌ ▐▌  █  ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌   
▐▛▀▜▌▐▌ ▐▌  █  ▐▛▀▜▌▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖
▐▌ ▐▌▝▚▄▞▘  █  ▐▌ ▐▌▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘
                                   
                                   
                                   
@baseUrl = http://localhost:4000/api

### Get all authors
GET {{baseUrl}}/authors
Accept: application/json

### Get author by id
GET {{baseUrl}}/authors/1
Accept: application/json

### Create a new author
POST {{baseUrl}}/authors
Content-Type: application/json
Accept: application/json  

{
  "first_name": "J.R.R.",
  "last_name": "Tolkien",
  "birth_date": "1892-01-03"
}

### Update an author
PATCH {{baseUrl}}/authors/11
Content-Type: application/json
Accept: application/json  

{
  "first_name": "John Ronald Reuel"
}

### Delete an author
DELETE {{baseUrl}}/authors/11
Accept: application/json
