#                                     #
# ▗▄▄▖  ▗▄▖ ▗▄▄▖ ▗▄▄▖  ▗▄▖ ▗▖ ▗▖ ▗▄▄▖ #
# ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌    #
# ▐▛▀▚▖▐▌ ▐▌▐▛▀▚▖▐▛▀▚▖▐▌ ▐▌▐▌ ▐▌ ▝▀▚▖ #
# ▐▙▄▞▘▝▚▄▞▘▐▌ ▐▌▐▌ ▐▌▝▚▄▞▘▐▙█▟▌▗▄▄▞▘ #
#                                     #
#                                     #

@baseUrl = http://localhost:4000/api

### Get all borrows
GET {{baseUrl}}/borrows
Accept: application/json

### Get borrow by id
GET {{baseUrl}}/borrows/1
Accept: application/json