▗▖  ▗▖ ▗▄▖▗▄▄▄▖▗▄▄▄▖ ▗▄▄▖
▐▛▚▖▐▌▐▌ ▐▌ █  ▐▌   ▐▌   
▐▌ ▝▜▌▐▌ ▐▌ █  ▐▛▀▀▘ ▝▀▚▖
▐▌  ▐▌▝▚▄▞▘ █  ▐▙▄▄▖▗▄▄▞▘


@baseUrl = http://localhost:4000/api

### Get all borrowers
GET {{baseUrl}}/notes
Accept: application/json